framework:
    cache:

        # https://symfony.com/doc/current/cache.html
        # Pour vider le cache : php bin/console cache:pool:clear --all

        app: 'cache.adapter.filesystem'

        pools:

            # En RAM
            memory_cache:
                # autowireable via "CacheInterface $memoryCache"
                adapter: cache.adapter.array

            # Dans les fichiers, dans ./var/cache/{env}/pools/app
            filesystem_cache:
                # autowireable via "CacheInterface $filesystemCache"
                adapter: cache.adapter.filesystem

