monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:

            # Fichier et symfony serve [Application]
            file:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!deprecation"]

            # Fichie séparé pour les dépréciations
            deprecation:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
                level: info
                channels: [ "deprecation" ]

            stderr:
                type: stream
                path: php://stderr
                level: error

            # Commandes
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:

            # On affiche en console uniquement les erreurs, accompagnés des autre logs
            filter_error:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
                channels: ["!event", "!deprecation"]
            nested:
                type: stream
                path: php://stderr
                level: debug

            # Dans le fichier on met tout, sauf le debug
            file:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: info
                channels: ["!event", "!deprecation"]

            # Pour les commandes, on affiche tout
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!deprecation"]
